services:
  app:
    image: askcos2-core:dev
    hostname: app
    restart: always
    env_file:
      - .env
    command: bash -l -c "python app.py"
    ports:
      - "9100:9100"

  rabbitmq:
    image: rabbitmq:3.11-alpine
    hostname: rabbitmq
    restart: always
    expose:
      - "${RABBITMQ_PORT}"

  redis:
    image: redis:7.0-alpine
    hostname: redis
    env_file:
      - .env
    restart: always
    expose:
      - "${REDIS_PORT}"
    volumes:
      - "redisdata:/data"
    command: redis-server --port ${REDIS_PORT}

  generic_worker:
    image: askcos2-core:dev
    restart: always
    env_file:
      - .env
    command: bash -l -c "celery -A askcos2_celery worker -c 1 -Q generic -n generic_worker@%h --pool=gevent"
    depends_on:
      - rabbitmq
      - redis

volumes:
  redisdata:
