services:
  app:
    image: ${ASKCOS_REGISTRY}/askcos2_core:2.0
    hostname: app
    restart: always
    env_file:
      - .env
    network_mode: host
    volumes:
      - "./data/db:/usr/local/askcos-data/db"
    command: python app.py
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0.9-jammy
    hostname: mongo
    restart: always
    env_file:
      - .env
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - "askcosv2_mongo_data:/data/db"
      - "./data/db:/usr/local/askcos-data/db"
    command: --wiredTigerCacheSizeGB 1.5

  rabbitmq:
    image: rabbitmq:3.11-alpine
    hostname: rabbitmq
    restart: always
    env_file:
      - .env
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"

  redis:
    image: redis:7.0-alpine
    hostname: redis
    restart: always
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - "askcosv2_redisdata:/data"
    command: redis-server --port ${REDIS_PORT}

  celery_workers:
    image: ${ASKCOS_REGISTRY}/askcos2_core:2.0
    restart: always
    env_file:
      - .env
    network_mode: host
    command: sh scripts/start_celery_workers.sh
    depends_on:
      - rabbitmq
      - redis

volumes:
  askcosv2_redisdata:
  askcosv2_mongo_data:
